### ISSUE TITLE
Instructions to start

### ISSUE THREAD

**Issue by alexismeza** [mezae/Winter-Wishes#1]
Can you post some instructions on how to start, either on the README.md or the wiki.  I'm not sure where it belongs but I'll get back to you on that. I cloned your repo but I don't know if I should have grunt do something or bower. Thanks!

**Comment by mezae** [comment]
http://meanjs.org/docs.html
Check out the prerequisites section, then quick install, then running your
app
I'll add those to the readme tonight

**Comment by mezae** [comment]
thanks for taking care of it
